# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#  view:
#    formats: { json: true, xml: false, rss: false }
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
  view:
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  serializer:
    serialize_null: true
  format_listener:
    rules:
      - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ] }
  param_fetcher_listener: true
  exception:
    enabled: true
    codes:
      App\Exception\ResourceValidationException: 400
      App\Exception\AccessException: 403
    messages:
      App\Exception\ResourceValidationException: true
      App\Exception\AccessException: true